server {
    listen 80;
    server_name _;

    root /home/toolbox/frontend;
    index index.html;

    include /etc/nginx/conf.d/toolbox-locations.inc;
}

server {
    listen 80;
    server_name bangong02.com www.bangong02.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bangong02.com www.bangong02.com _;
    ssl_certificate /etc/letsencrypt/live/bangong02.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bangong02.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /home/toolbox/frontend;
    index index.html;

    include /etc/nginx/conf.d/toolbox-locations.inc;
}
